# Generated by Django 4.2.7 on 2024-01-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0007_rename_text_article_description_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='specification',
            field=models.CharField(default='', max_length=255),
        ),
    ]
