# Generated by Django 4.2.7 on 2024-01-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0013_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
