# Generated by Django 4.2.7 on 2024-01-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0016_remove_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='specification',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
