# Generated by Django 4.2.7 on 2023-12-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhlArticles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imageSource',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
    ]
