# Generated by Django 4.2.7 on 2023-12-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhlArticles', '0002_alter_article_imagesource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imageSource',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
