# Generated by Django 4.2.7 on 2023-12-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhlArticles', '0003_alter_article_imagesource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='imageSource',
            new_name='image',
        ),
    ]
